# Generated by Django 5.2.1 on 2025-06-02 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Jméno postavy (povinné)', max_length=100)),
                ('rasa', models.CharField(help_text='Rasa postavy, např. Člověk, Elf, Trpaslík (povinné)', max_length=50)),
                ('trida', models.CharField(help_text='Třída postavy, např. Válečník, Kouzelník, Tulák (povinné)', max_length=50)),
                ('uroven', models.IntegerField(default=1, help_text='Úroveň postavy (1-20, povinné)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('zivotopis', models.TextField(blank=True, help_text='Krátký životopis nebo poznámky k postavě (volitelné)', null=True)),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True, help_text='Datum a čas vytvoření záznamu postavy')),
                ('sila', models.IntegerField(blank=True, help_text='Hodnota síly postavy (1-30, volitelné)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('je_aktivni', models.BooleanField(default=True, help_text='Označuje, zda je postava aktivně používána (povinné)')),
            ],
            options={
                'verbose_name': 'Postava',
                'verbose_name_plural': 'Postavy',
                'ordering': ['jmeno'],
            },
        ),
    ]
